// Complete list of major hospitals in Faisalabad, Punjab, Pakistan
export const FAISALABAD_HOSPITALS = [
  "Allied Hospital Faisalabad",
  "DHQ Teaching Hospital Faisalabad",
  "Punjab Institute of Cardiology Faisalabad",
  "Children Hospital & Institute of Child Health Faisalabad",
  "Faisalabad Institute of Cardiology",
  "Sir Ganga Ram Hospital Faisalabad",
  "Civil Hospital Faisalabad",
  "Majeed Hospital Faisalabad",
  "Al Shifa Hospital Faisalabad",
  "National Hospital Faisalabad",
  "City Hospital Faisalabad",
  "Iqbal Hospital Faisalabad",
  "Fatima Hospital Faisalabad",
  "Aziz Fatima Hospital Faisalabad",
  "Medicare Hospital Faisalabad",
  "Life Hospital Faisalabad",
  "Shalamar Hospital Faisalabad",
  "Rashid Hospital Faisalabad",
  "Jinnah Hospital Faisalabad",
  "Muslim Hospital Faisalabad",
  "Ameer Hospital Faisalabad",
  "Faisal Hospital Faisalabad",
  "Sahara Hospital Faisalabad",
  "Ghurki Trust Teaching Hospital Faisalabad",
  "Wapda Hospital Faisalabad",
  "Railway Hospital Faisalabad",
  "PAF Hospital Faisalabad",
  "CMH Faisalabad",
  "Social Security Hospital Faisalabad",
  "Industrial Hospital Faisalabad",
  "Layton Rahmatulla Benevolent Trust Hospital",
  "Al Noor Hospital Faisalabad",
  "Shaheen Hospital Faisalabad",
  "Farooq Hospital Faisalabad",
  "Hameed Memorial Hospital",
  "Nawaz Sharif Hospital Faisalabad",
  "Ibn-e-Sina Hospital Faisalabad",
  "Maryam Memorial Hospital",
  "Prime Hospital Faisalabad",
  "Chaudhary Hospital Faisalabad",
  "Sadiq Memorial Hospital",
  "Zainab Memorial Hospital",
  "Afaq Hospital Faisalabad",
  "Madina Hospital Faisalabad",
  "Noor Hospital Faisalabad",
  "Arooj Hospital Faisalabad",
  "Usman Hospital Faisalabad",
  "Taj Hospital Faisalabad",
  "Star Hospital Faisalabad",
  "Green Hospital Faisalabad",
  "Royal Hospital Faisalabad",
  "Liaquat National Hospital Faisalabad",
  "University Medical & Dental College Hospital",
  "Punjab Medical College Teaching Hospital",
  "Independent Hospital Faisalabad",
  "Central Hospital Faisalabad",
  "District Headquarters Hospital",
  "Tehsil Headquarters Hospital Samundri",
  "Tehsil Headquarters Hospital Tandlianwala",
  "Tehsil Headquarters Hospital Jaranwala",
  "Rural Health Centers Faisalabad"
]