import getDB from "@/config/database"
import Patient from "@/models/Patient"
import { jsPDF } from "jspdf"

// Helper function to format dates
const formatDate = (date) => {
  if (!date) return "Not set"
  return new Date(date).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric"
  })
}

const formatDateTime = (date) => {
  if (!date) return "N/A"
  return new Date(date).toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  })
}

// GET - Generate and download EHR report as PDF
export async function GET(request, { params }) {
  try {
    await getDB()
    const { patientId } = await params
    
    const patientCollection = Patient.getCollection()
    const patient = await patientCollection.findOne({ patientId })
    
    if (!patient) {
      return Response.json({ success: false, error: "Patient not found" }, { status: 404 })
    }
    
    // Generate PDF
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const contentWidth = pageWidth - (margin * 2)
    let y = 20
    
    // Header
    doc.setFillColor(56, 117, 253)
    doc.rect(0, 0, pageWidth, 40, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(24)
    doc.setFont("helvetica", "bold")
    doc.text("ELECTRONIC HEALTH RECORD", pageWidth / 2, 25, { align: "center" })
    doc.setFontSize(12)
    doc.text("Generated by MedPulse", pageWidth / 2, 35, { align: "center" })
    
    // Patient Information Section
    y = 55
    doc.setTextColor(2, 3, 49)
    doc.setFontSize(16)
    doc.setFont("helvetica", "bold")
    doc.text("PATIENT INFORMATION", margin, y)
    
    y += 10
    doc.setDrawColor(56, 117, 253)
    doc.setLineWidth(0.5)
    doc.line(margin, y, pageWidth - margin, y)
    
    y += 15
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(100, 100, 100)
    
    // Two-column layout for patient info
    const leftCol = margin
    const rightCol = pageWidth / 2 + 10
    
    // Left column
    doc.text(`Patient ID:`, leftCol, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.patientId}`, leftCol + 40, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`First Name:`, leftCol, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.firstName}`, leftCol + 40, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`Last Name:`, leftCol, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.lastName}`, leftCol + 40, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`Date of Birth:`, leftCol, y)
    doc.setTextColor(2, 3, 49)
    doc.text(formatDate(patient.dateOfBirth), leftCol + 45, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`Gender:`, leftCol, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.gender?.charAt(0).toUpperCase() + patient.gender?.slice(1) || "Not set"}`, leftCol + 25, y)
    
    // Right column
    y = 70
    doc.setTextColor(100, 100, 100)
    doc.text(`Email:`, rightCol, y)
    doc.setTextColor(2, 3, 49)
    const emailText = patient.email.length > 25 ? patient.email.substring(0, 25) + "..." : patient.email
    doc.text(emailText, rightCol + 30, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`Phone:`, rightCol, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.phone || patient.phoneNumber || "Not set"}`, rightCol + 30, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`Blood Group:`, rightCol, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.bloodGroup || "Not set"}`, rightCol + 45, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`Weight:`, rightCol, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.weight ? patient.weight + " kg" : "Not set"}`, rightCol + 25, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`Height:`, rightCol, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.height ? patient.height + " cm" : "Not set"}`, rightCol + 25, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`BMI:`, rightCol, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.bmi ? patient.bmi.toFixed(1) : "N/A"}`, rightCol + 20, y)
    
    // Emergency Contact Section
    y += 15
    if (y > 250) {
      doc.addPage()
      y = 20
    }
    
    doc.setFontSize(16)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(2, 3, 49)
    doc.text("EMERGENCY CONTACT", margin, y)
    
    y += 10
    doc.setLineWidth(0.5)
    doc.line(margin, y, pageWidth - margin, y)
    
    y += 15
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(100, 100, 100)
    doc.text(`Name:`, margin, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.emergencyContact?.name || "Not set"}`, margin + 30, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`Relationship:`, margin, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.emergencyContact?.relationship || "Not set"}`, margin + 55, y)
    
    y += 8
    doc.setTextColor(100, 100, 100)
    doc.text(`Phone:`, margin, y)
    doc.setTextColor(2, 3, 49)
    doc.text(`${patient.emergencyContact?.phone || "Not set"}`, margin + 30, y)
    
    if (patient.emergencyContact?.alternatePhone) {
      y += 8
      doc.setTextColor(100, 100, 100)
      doc.text(`Alt Phone:`, margin, y)
      doc.setTextColor(2, 3, 49)
      doc.text(`${patient.emergencyContact.alternatePhone}`, margin + 45, y)
    }
    
    if (patient.emergencyContact?.address) {
      y += 8
      doc.setTextColor(100, 100, 100)
      doc.text(`Address:`, margin, y)
      doc.setTextColor(2, 3, 49)
      // Wrap address if too long
      const address = patient.emergencyContact.address
      const splitAddress = doc.splitTextToSize(address, contentWidth - 30)
      doc.text(splitAddress, margin + 40, y)
    }
    
    // Allergies Section
    y += 15
    if (y > 250) {
      doc.addPage()
      y = 20
    }
    
    doc.setFontSize(16)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(2, 3, 49)
    doc.text("ALLERGIES", margin, y)
    
    y += 10
    doc.line(margin, y, pageWidth - margin, y)
    
    y += 15
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    
    if (patient.allergies && patient.allergies.length > 0) {
      doc.setTextColor(239, 68, 68)
      doc.setFont("helvetica", "bold")
      patient.allergies.forEach((allergy) => {
        if (y > 280) {
          doc.addPage()
          y = 20
        }
        doc.text(`• ${allergy}`, margin, y)
        y += 8
      })
    } else {
      doc.setTextColor(34, 197, 94)
      doc.setFont("helvetica", "italic")
      doc.text("No known allergies", margin, y)
    }
    
    // Chronic Conditions Section
    y += 10
    if (y > 250) {
      doc.addPage()
      y = 20
    }
    
    doc.setFontSize(16)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(2, 3, 49)
    doc.text("CHRONIC CONDITIONS", margin, y)
    
    y += 10
    doc.line(margin, y, pageWidth - margin, y)
    
    y += 15
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    
    if (patient.chronicConditions && patient.chronicConditions.length > 0) {
      doc.setTextColor(239, 68, 68)
      patient.chronicConditions.forEach((condition) => {
        if (y > 280) {
          doc.addPage()
          y = 20
        }
        doc.text(`• ${condition}`, margin, y)
        y += 8
      })
    } else {
      doc.setTextColor(34, 197, 94)
      doc.setFont("helvetica", "italic")
      doc.text("No chronic conditions recorded", margin, y)
    }
    
    // Current Medications Section
    y += 10
    if (y > 250) {
      doc.addPage()
      y = 20
    }
    
    doc.setFontSize(16)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(2, 3, 49)
    doc.text("CURRENT MEDICATIONS", margin, y)
    
    y += 10
    doc.line(margin, y, pageWidth - margin, y)
    
    y += 15
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    
    if (patient.currentMedications && patient.currentMedications.length > 0) {
      patient.currentMedications.forEach((med) => {
        if (y > 280) {
          doc.addPage()
          y = 20
        }
        
        doc.setFont("helvetica", "bold")
        doc.setTextColor(2, 3, 49)
        doc.text(`${med.name || "Medicine"}`, margin, y)
        
        y += 6
        doc.setFont("helvetica", "normal")
        doc.setTextColor(100, 100, 100)
        
        let details = []
        if (med.dosage) details.push(`Dosage: ${med.dosage}`)
        if (med.frequency) details.push(`Frequency: ${med.frequency}`)
        if (med.startDate) details.push(`Since: ${formatDate(med.startDate)}`)
        
        details.forEach(detail => {
          if (y > 280) {
            doc.addPage()
            y = 20
          }
          doc.text(`  ${detail}`, margin + 5, y)
          y += 6
        })
        
        if (med.prescribedBy) {
          if (y > 280) {
            doc.addPage()
            y = 20
          }
          doc.text(`  Prescribed by: ${med.prescribedBy}`, margin + 5, y)
          y += 6
        }
        
        y += 4
      })
    } else {
      doc.setTextColor(34, 197, 94)
      doc.setFont("helvetica", "italic")
      doc.text("No current medications", margin, y)
    }
    
    // Assigned Doctors Section
    y += 10
    if (y > 250) {
      doc.addPage()
      y = 20
    }
    
    doc.setFontSize(16)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(2, 3, 49)
    doc.text("ASSIGNED DOCTORS", margin, y)
    
    y += 10
    doc.line(margin, y, pageWidth - margin, y)
    
    y += 15
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    
    if (patient.assignedDoctors && patient.assignedDoctors.length > 0) {
      patient.assignedDoctors.forEach((doctor) => {
        if (y > 280) {
          doc.addPage()
          y = 20
        }
        
        doc.setFont("helvetica", "bold")
        doc.setTextColor(2, 3, 49)
        doc.text(`Dr. ${doctor.doctorName}`, margin, y)
        
        y += 6
        doc.setFont("helvetica", "normal")
        doc.setTextColor(100, 100, 100)
        doc.text(`Specialization: ${doctor.specialization || "General"}`, margin + 5, y)
        
        if (doctor.assignedDate) {
          y += 6
          doc.text(`Assigned: ${formatDate(doctor.assignedDate)}`, margin + 5, y)
        }
        
        y += 8
      })
    } else {
      doc.setTextColor(100, 100, 100)
      doc.setFont("helvetica", "italic")
      doc.text("No assigned doctors", margin, y)
    }
    
    // Footer
    const totalPages = doc.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i)
      doc.setFontSize(9)
      doc.setTextColor(150, 150, 150)
      doc.text(
        `Generated on ${formatDateTime(new Date())} | Page ${i} of ${totalPages}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: "center" }
      )
      
      // MedPulse logo watermark
      doc.setFontSize(8)
      doc.text("MedPulse EHR System", pageWidth / 2, doc.internal.pageSize.getHeight() - 20, { align: "center" })
    }
    
    // Return PDF as blob
    const pdfBytes = doc.output("arraybuffer")
    const blob = new Blob([pdfBytes], { type: "application/pdf" })
    
    return new Response(blob, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="EHR_${patientId}_${new Date().toISOString().split('T')[0]}.pdf"`,
      },
    })
    
  } catch (error) {
    console.error("[API] Error generating EHR report:", error)
    return Response.json({ success: false, error: error.message }, { status: 500 })
  }
}
